"use client";

import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { PortalLogoPicker } from "@/components/app/portals/portal-logo-picker";
import { PortalSidebarPreview } from "@/components/app/portals/portal-sidebar-preview";

type PortalEditBrandingTabProps = {
  isPro: boolean;
  portalName: string;
  tagline: string;
  logoUrl: string | null;
  logoDraft: string | null;
  primaryColor: string;
  foregroundColor: string;
  hidePoweredBy: boolean;
  hidePdfBranding: boolean;
  initials: string;
  onLogoDraftChange: (dataUrl: string) => void;
  onPrimaryColorChange: (value: string) => void;
  onForegroundColorChange: (value: string) => void;
  onHidePoweredByChange: (value: boolean) => void;
  onHidePdfBrandingChange: (value: boolean) => void;
  disabled?: boolean;
};

export function PortalEditBrandingTab({
  isPro,
  portalName,
  tagline,
  logoUrl,
  logoDraft,
  primaryColor,
  foregroundColor,
  hidePoweredBy,
  hidePdfBranding,
  initials,
  onLogoDraftChange,
  onPrimaryColorChange,
  onForegroundColorChange,
  onHidePoweredByChange,
  onHidePdfBrandingChange,
  disabled,
}: PortalEditBrandingTabProps) {
  if (!isPro) {
    return (
      <div className="rounded-lg border border-border bg-muted/40 p-4 text-center space-y-2">
        <p className="text-sm font-medium">Pro feature</p>
        <p className="text-xs text-muted-foreground">
          Upgrade to Pro to customise your portal branding, including logo, colours, and PDF settings.
        </p>
      </div>
    );
  }

  return (
    <div className="flex gap-5">
      {/* Controls */}
      <div className="flex-1 space-y-4 min-w-0">
        {/* Logo */}
        <div className="space-y-1.5">
          <Label>Portal logo</Label>
          <p className="text-xs text-muted-foreground">Click the avatar to change.</p>
          <PortalLogoPicker
            logoSrc={logoDraft ?? logoUrl}
            initials={initials}
            onChange={onLogoDraftChange}
            disabled={disabled}
          />
        </div>

        {/* Background colour */}
        <div className="space-y-1.5">
          <Label htmlFor="edit-primary-color">Background colour</Label>
          <div className="flex items-center gap-2">
            <input
              id="edit-primary-color"
              type="color"
              value={primaryColor}
              onChange={(e) => onPrimaryColorChange(e.target.value)}
              disabled={disabled}
              className="size-8 cursor-pointer rounded-md border border-border bg-background p-0.5"
            />
            <span className="text-xs font-mono text-muted-foreground">{primaryColor}</span>
            <button
              type="button"
              onClick={() => onPrimaryColorChange("#0d9488")}
              className="ml-auto text-xs text-muted-foreground underline hover:text-foreground"
            >
              Reset
            </button>
          </div>
        </div>

        {/* Text colour */}
        <div className="space-y-1.5">
          <Label htmlFor="edit-foreground-color">Text colour</Label>
          <div className="flex items-center gap-2">
            <input
              id="edit-foreground-color"
              type="color"
              value={foregroundColor}
              onChange={(e) => onForegroundColorChange(e.target.value)}
              disabled={disabled}
              className="size-8 cursor-pointer rounded-md border border-border bg-background p-0.5"
            />
            <span className="text-xs font-mono text-muted-foreground">{foregroundColor}</span>
            <button
              type="button"
              onClick={() => onForegroundColorChange("#ffffff")}
              className="ml-auto text-xs text-muted-foreground underline hover:text-foreground"
            >
              Reset
            </button>
          </div>
        </div>

        {/* Toggles */}
        <div className="space-y-2 rounded-md border border-border p-3">
          <p className="text-xs font-medium">Visibility</p>
          <div className="flex items-center justify-between">
            <div>
              <Label htmlFor="edit-hide-powered-by">Hide &quot;Powered by Salkaro&quot;</Label>
              <p className="text-xs text-muted-foreground">Remove the footer attribution.</p>
            </div>
            <Switch
              id="edit-hide-powered-by"
              checked={hidePoweredBy}
              onCheckedChange={onHidePoweredByChange}
              disabled={disabled}
            />
          </div>
          <div className="flex items-center justify-between pt-1">
            <div>
              <Label htmlFor="edit-hide-pdf-branding">Remove Salkaro branding from PDF</Label>
              <p className="text-xs text-muted-foreground">Hides &quot;Generated by Salkaro Portals&quot;.</p>
            </div>
            <Switch
              id="edit-hide-pdf-branding"
              checked={hidePdfBranding}
              onCheckedChange={onHidePdfBrandingChange}
              disabled={disabled}
            />
          </div>
        </div>
      </div>

      {/* Live preview */}
      <div className="w-44 shrink-0 space-y-1.5">
        <p className="text-xs font-medium text-muted-foreground">Preview</p>
        <div className="h-72 overflow-hidden rounded-lg border border-border">
          <PortalSidebarPreview
            portalName={portalName || "Portal"}
            tagline={tagline || undefined}
            logoSrc={logoDraft ?? logoUrl}
            primaryColor={primaryColor}
            foregroundColor={foregroundColor}
            hidePoweredBy={hidePoweredBy}
          />
        </div>
        <p className="text-[10px] text-muted-foreground text-center">Sidebar preview</p>
      </div>
    </div>
  );
}
